baseURL = "http://localhost:1313/"
languageCode = "en-us"
title = "Alonso Palomino"
theme = "hyde"

[pagination]
  pagerSize = 10

[params]
  mainSections = ["posts"]
  customCSS = ["css/custom.css"]


[menu]
  [[menu.main]]
    name = "Experience"
    url = "/experience/"
    weight = 2

  [[menu.main]]
    name = "Publications"
    url = "/publications/"
    weight = 3

  # [[menu.main]]
  #   name = "Education"
  #   url = "/education/"
  #   weight = 4

  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 5


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

