baseURL = "https://alonsopg.github.io/"
languageCode = "en-us"
title = "Alonso Palomino"
theme = "hyde"
publishDir = "docs"            # <- GitHub Pages will serve from /docs

[pagination]
  pagerSize = 10

[params]
  mainSections = ["posts"]
  customCSS = ["css/custom.css"]

[menu]
  [[menu.main]]
    name = "Experience"
    url  = "/experience/"
    weight = 1

  [[menu.main]]
    name = "Demos"
    url  = "/demos/"
    weight = 2

  [[menu.main]]
    name = "Publications"
    url  = "/publications/"
    weight = 3

  [[menu.main]]
    name = "Contact"
    url  = "/contact/"
    weight = 4

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
